* 1.38d, 1 December 2006       + Added a "Light Background" option to Process/Binary/Find Maxima.       + Changed the "White Background" option in Process/Subtract Background to         "Light Background". Macros that use the "white" keyword will continue         to work.       + Added the Prefs.setImageURL() method, which can be called from the         "AutoRun" macro in the StartupMacros to specify the directory used to         load the sample images.       + Fixed a bug, introduced in 1.38c, that caused the Image5D plugin to         generate a NoSuchMethodError exception.
git-svn-id: http://code.imagej.net/svn/imagej/branches/ijx@166 be23795f-a60e-40d4-ba19-055798872e57